version: '3.7'
services:
  services-registry:
    build: services-registry
    ports:
      - "8761:8761"
    networks:
      - shop_app-networks
  products-service:
    build: products-service
    ports:
      - "8080:8080"
    networks:
      - shop_app-networks
    environment:
      EUREKA_URL: http://services-registry:8761/eureka
      DB_URL: jdbc:mysql://shop_db:3306/products-service?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    depends_on:
      - services-registry
      - shop_db
  shopcarts-service:
    build: shopcarts-service
    ports:
      - "8081:8081"
    networks:
      - shop_app-networks
    environment:
      EUREKA_URL: http://services-registry:8761/eureka
      DB_URL: jdbc:mysql://shop_db:3306/shopcarts-service?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    depends_on:
      - services-registry
      - shop_db
  sells-service:
    build: sells-service
    ports:
      - "8082:8082"
    networks:
      - shop_app-networks
    environment:
      EUREKA_URL: http://services-registry:8761/eureka
      DB_URL: jdbc:mysql://shop_db:3306/sells-service?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    depends_on:
      - services-registry
      - shop_db
  api-gateway:
    build: api-gateway
    ports:
      - "443:443"
    networks:
      - shop_app-networks
    environment:
      EUREKA_URL: http://services-registry:8761/eureka
    depends_on:
      - services-registry
  shop_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - shop_app-networks
networks:
  shop_app-networks: